lang: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install --user nose2 coverage cov-core coveralls
script:
  - nose2
after-success:
  - coveralls
cache: pip
notifications:
  email: false